version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - astro
          - '*astro*'
      eslint:
        patterns:
          - eslint*
          - '@eslint/*'
          - typescript-eslint
      prettier:
        patterns:
          - prettier*
      tailwind:
        patterns:
          - tailwindcss
          - '@tailwindcss/*'
      typescript:
        patterns:
          - typescript
      git-hooks:
        patterns:
          - husky
          - lint-staged
      other:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
